### ISSUE TITLE
TPS lag from blade trap

### ISSUE THREAD

**Issue by LemADEC** [Sunconure11/dungeon-mobs#20]
As of 1.12.2-1.4.0, blade trap are using ~1% server CPU by itself.

![image](https://user-images.githubusercontent.com/4776032/43616147-63b19848-96bb-11e8-8aa9-4c1988df977f.png)

`world.getEntitiesWithinAABB()` is very slow, should be only called as a last resort, every ticks.
Current version is calling it every ticks, for every tile entities.

Consider scanning the player list instead of all entities, using `world.getPlayers()`.
Consider checking for players only every few seconds with a bit of randomness.

**Comment by BlackJar72** [comment]
I'll look into this.  This was always a great mod, though until I took over it and saw the source code I had no idea how unoptimized it was.  I've been trying to fix some of this with, but this slipped by.

Checking the player list would make more since in general.  Don't know how some -- this isn't my only, or favorite project, and then there's real life.  But this should not be that complicated to fix (unlike lizalfos, which may stay broken).

**Comment by BlackJar72** [comment]
I've fixed this in the code / dev version -- it should be fixed in the next release.
